name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Run SonarQube analysis
        run: |
          ./gradlew build sonar \
            -Dsonar.gradle.skipCompile=true \
            -Dsonar.projectKey=Liferay-Workspace \
            -Dsonar.projectName="Liferay Workspace" \
            -Dsonar.sources=client-extensions \
            -Dsonar.test.inclusions=**/__tests__/**,**/*.test.js,**/*.test.jsx,**/*.test.tsx \
            -Dsonar.test.exclusions=**/node_modules/**,**/build/**,**/dist/** \
            -Dsonar.tests="" \
            -Dsonar.scm.disabled=true \
            -Dsonar.host.url=https://731088a60de3.ngrok-free.app \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
